version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_AIRPORT_API_URL=https://aviation-edge.com/v2/public/autocomplete
      - REACT_APP_AVIATION_API_KEY=${AVIATION_API_KEY}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/flight-booking
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - PORT=5000
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
